algoritmo "Atividade03"
//3) Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
var
salario: real
nome: caractere
inicio
escreva("Nome do Funcionário: ")
leia(nome)
escreva("Salário: ")
leia(salario)
escreval("O(A) Funcionário(a) ",nome," tem um salário de R$",salario," em Junho.")
fimalgoritmo
