Algoritmo "ex64"
// Lógica de Programação
// Professor: Gustavo Guanabara 
// Descrição: 64) Desenvolva um programa usando a estrutura “para”
//que mostre na tela a seguinte contagem:
// 0 5 10 15 20 25 30 35 40 Acabou!
// Autor: Leonardo
// Data atual  : 18/01/2023
Var
   cont: inteiro

Inicio
   para cont <- 0 ate 40 passo 5 faca
       escreval(cont)
   fimpara
   escreval("Acabou!")
Fimalgoritmo