Algoritmo "ex65"
// Lógica de Programação
// Professor: Gustavo Guanabara 
// Descrição: 65) Desenvolva um programa usando a estrutura “para”
//que mostre na tela a seguinte contagem:
//100 90 80 70 60 50 40 30 20 10 0 Acabou!
// Autor: Leonardo
// Data atual: 18/01/2023
Var
   cont: inteiro

Inicio
   para cont <- 100 ate 0 passo -10 faca
      escreval(cont)
   fimpara
   escreval("Acabou!")
Fimalgoritmo